### ISSUE TITLE
Credit needs to be preserved

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#14]
Somewhere we need to name contributes and dates!

**Comment by 4pins** [comment]
Where and What?  We know we want to keeping credit for the IEP, probably in an appendix.

**Comment by tqwhite** [comment]
Annotation block. 


-----------------------------------

TQ White II
708-763-0100

**Comment by 4pins** [comment]
According to an email TQ II sent Penny, it is okay to add this to xs:documentation.

**Comment by 4pins** [comment]
Penny wants us to also make sure we reference the "Access 4 Learning Community."

**Comment by 4pins** [comment]
John Lovell, Access for Learning -> John Lovell, Access 4 Learning Community

**Comment by tqwhite** [comment]
That’s great. I think you should add your title, too. 

John Lovell, Access for Learning -> John Lovell, Cat Herder, Access 4 Learning Community
tqii
TQ White II
Website • blog.genericwhite.com
Phone • 708-763-0100

**Comment by 4pins** [comment]
Added to xIndividualizedEducationPlan's documentation.
