### ISSUE TITLE
P-POD Covers More Than Privacy

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#146]
Suggest bulking up the current description to include other covered areas.

"This object contains information about the person's data and privacy obligations associated with it."

Consider adding "Document" to the end of the name to align with POD and P-POD acronym.

**Comment by LindaNSIP** [comment]
Name changed to Personal Privacy Obligation Document and description updated

**Comment by 4pins** [comment]
Confirmed!

![image](https://user-images.githubusercontent.com/10967355/116596465-3d046580-a8d9-11eb-9837-f67181810438.png)
