### ISSUE TITLE
P-POD:  Need to know who consented or gave permission.

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#147]
RefId & ObjectType on _each_!

**Comment by 4pins** [comment]
NC:  Would like the option of not having to use a RefId to indicate who.  I think in order to be international in nature we would want a simple text field. I'd suggest, "PersonWhoConsented" & "PersonWhoGavePermission."

**Comment by 4pins** [comment]
The relationship (self, parent, guardian, principal, etc.) is more important than the name, but both would be nice.

**Comment by LindaNSIP** [comment]
Name and Relationship elements added but description is if Object details unknow.

**Comment by 4pins** [comment]
I added four fields to track the Permission Grantee.

**Comment by 4pins** [comment]
Here is what it looks like!

![PersonPrivacyObligationDocuments](https://user-images.githubusercontent.com/10967355/115740239-7a9a4900-a343-11eb-8d5b-bd6a77e3e16b.png)

**Comment by 4pins** [comment]
Updated to address systemic concerns.

![PersonPrivacyObligationDocuments](https://user-images.githubusercontent.com/10967355/115967592-57f56500-a4e8-11eb-946d-984708ab4fc2.jpg)

**Comment by 4pins** [comment]
Confirmed!  We may want to clarify in the descriptions of these fields that these track the person giving/rejecting consent or permission and not necessarily the person impacted.
