### ISSUE TITLE
P-POD:  Add [Prefix]ShareWithObjectType throughout.

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#148]
Wherever RefId appears:  ShareWithObjecType, DoNotShareWithObjecType, and NeverShareWithObjecType.

**Comment by LindaNSIP** [comment]
RefId_Object element added as a string for each place

**Comment by 4pins** [comment]
Names coppied and pasted from the draft: ShareWithRefId_Object, DoNotShareWithRefId_Object, NeverShareWithRefId_Object

**Comment by 4pins** [comment]
After back and forth wound up here (results currently being shared with the AU contingent):

Resolve to send (to all interested parties and the NATB) the following text to the ITB as feedback and implementation in the PPod:

The proposed names are actively misleading.

PermissionGranteeObjectRefId PermissionGranteeRefId_object

It suggests that the data element has both a refId and the object data including the refId.

I suggest a more informative alternative.

PermissionGranteeRefId PermissionGranteeObjectTypeName

The phrase 'PermissionGrantee' serves to group the two elements.

PermissionGranteeRefId is a normal SIF thing and makes sense here.

The phrase 'PermissionGranteeObjectTypeName' indicates to a programmer that the phrase is a string that says what the type is.

The other elements with this patter, eg, ContactForRequests, should be changed to follow this pattern.

The Location element should be entirely replaced with new elements that follow this pattern.

**Comment by 4pins** [comment]
In place.  We don't expect any further push back.
