### ISSUE TITLE
Missing Alignment to CEDS: Assessment Purpose (000026)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#166]
CEDS element 000026 (Assessment Purpose) as referenced by domain entity Assessments -> Assessment in the Assessment ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Suspect that /Assessment​/AssessmentDescriptors​/AssessmentDescriptor should be mapped to CEDS Assessment Type (000029).

**Comment by 4pins** [comment]
Gap confirmed!  Should be added to Unity in Assessment (parallel to AssessmentDescriptor).

**Comment by tqwhite** [comment]
NATB agrees. CEDS is not in place.

**Comment by tqwhite** [comment]
http://specification.sifassociation.org/Implementation/NA/4.3/AssessmentWorkingGroup.html#obj:Assessment

**Comment by 4pins** [comment]
It is there (see: AssessmentPurpose).

**Comment by 4pins** [comment]
Added to mapping (Assessments)!
