### ISSUE TITLE
Missing Alignment to CEDS: Assessment Title (000028)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#167]
CEDS element 000028 (Assessment Title) as referenced by domain entity Assessments -> Assessment in the Assessment ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
While present in Unity, needs to be included in the EDFacts Mapping update!

**Comment by 4pins** [comment]
Added to mapping (Assessments)!
