### ISSUE TITLE
Missing Alignment to CEDS: Assessment Type (000029)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#168]
CEDS element 000029 (Assessment Type) as referenced by domain entity Assessments -> Assessment in the Assessment ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Map /Assessment​/AssessmentDescriptors​/AssessmentDescriptor should be mapped to CEDS Assessment Type (000029).

**Comment by 4pins** [comment]
Duplicate of https://github.com/Access4LearningNA/specgen_input_na/issues/166.

**Comment by tqwhite** [comment]
NATB agree it should happen but it has not been done yet.

**Comment by tqwhite** [comment]
http://specification.sifassociation.org/Implementation/NA/4.3/AssessmentWorkingGroup.html#obj:Assessment

**Comment by 4pins** [comment]
Looks done to me:  http://specification.sifassociation.org/Implementation/NA/4.3/CommonTypes.html#AssessmentDescriptorListType

**Comment by 4pins** [comment]
Added to mapping (Assessments)!
