### ISSUE TITLE
Missing Alignment to CEDS: Middle Name (000184)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#169]
CEDS element 000184 (Middle Name) as referenced by domain entity K12 -> K12 Staff -> Identity -> Name in the Personnel ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Add mapping to both:  /StaffPersonal​/Name​/MiddleName & /EmployeePersonal​/Name​/MiddleName

**Comment by tqwhite** [comment]
http://specification.sifassociation.org/Implementation/NA/4.3/CommonTypes.html#NameOfRecordType

**Comment by tqwhite** [comment]
NameOfRecordType/MiddleName has 184. NATB reviewed and approve 7/21/22

**Comment by 4pins** [comment]
So the mapping doesn't have a "Personnel" section.  Will discuss with John P. on tomorrows call.

**Comment by 4pins** [comment]
Good to go!
