### ISSUE TITLE
xPress Working Group, many Type links in tables are incorrect

### ISSUE THREAD

**Issue by cvioletti** [Access4LearningNA/specgen_input_na#17]
- xContact
  - xPersonNameTypeType invalid page anchor. I would expect this to take you to A.131 name in the appendix. This name object also includes address information, which I don't think is right. The links to name__type in this object also do not work. It looks like another case sensitivity issue in page anchors. 
  - xPersonIdSystemType links to it's code set.
  - xCountryCodeType invalid page anchor.
  - xEmailTypeType invalid page anchor.
  - xSexType links to it's code set.
  - xEmployerType links to it's code set.
- xCourse
  - xCourseCodeSystemType invalid page anchor.
  - xGradeLevelType invalid page anchor.
- xLea
  - xCountryCodeType invalid page anchor.
- xRoster
  - Element meetingTimes has incorrect Type link to xExitOrWithdrawalType which is an invalid page anchor anyway.
- xSchool
  - xGradeLevelType invalid page anchor.
  - xCountryCodeType invalid page anchor.
- xStaff
  - xPersonNameTypeType invalid page anchor.
  - xPersonIdSystemType links to it's code set.
  - xSexType links to it's code set.
  - xEmailTypeType invalid page anchor.
  - xEducationStaffClassificationType invalid page anchor.
- xStudent
  - xPersonNameTypeType invalid page anchor.
  - xPersonIdSystemType links to it's code set.
  - xCountryCodeType invalid page anchor.
  - xStateCodeUSType invalid page anchor.
  - xEmailTypeType invalid page anchor.
  - xLanguageTypeType invalid page anchor.
- xTransferIEP
  - xAddressTypeForOrganizationType invalid page anchor.

**Comment by 4pins** [comment]
@cvioletti Sure and let's not wait too long.  Tomorrow after 10 AM Pacific works for me!

**Comment by cvioletti** [comment]
@4pins, My calendar is totally blown tomorrow BUT, I suspect a meeting I have in the afternoon will run short. I'll let you know or follow up in the evening with my availability on Wednesday.

**Comment by 4pins** [comment]
@4pins Be sure you do!  I'd say we need to connect before Friday.

**Comment by cvioletti** [comment]
These are all now working!
