### ISSUE TITLE
Missing Alignment to CEDS: Number of Days in Attendance (000202)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#170]
CEDS element 000202 (Number of Days in Attendance) as referenced by domain entity K12 -> K12 Student -> Attendance in the OESE ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Update /StudentAttendanceSummary/DaysAttended (currently mapped to 000271) to Number of Days in Attendance (000202).

**Comment by tqwhite** [comment]
http://specification.sifassociation.org/Implementation/NA/4.3/StudentInformationSystemsWorkingGroup.html#obj:StudentAttendanceSummary

**Comment by tqwhite** [comment]
DayAttended element has 202. NATB reviewed and approved 7/21/22

**Comment by 4pins** [comment]
Added to mapping (Attendance)!
