### ISSUE TITLE
Missing Alignment to CEDS: Assessment Family Title (000932)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#173]
CEDS element 000932 (Assessment Family Title) as referenced by domain entity Assessments -> Assessment in the Assessment ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
NATB has choices:
- Add AssessmentFamilyTitle to the Unity Assessment object (current CEDS approach).
- Add separate AssessmentFamily object to Unity with Title and possibly Provider.

**Comment by ajackl** [comment]
Object referenced in the Ticket: http://specification.sifassociation.org/Implementation/NA/4.3/AssessmentWorkingGroup.html#obj:Assessment

**Comment by ajackl** [comment]
John , Jeff, and Alex believe the first bullet is the right approach.  John will do that.

**Comment by 4pins** [comment]
Added to mapping (Assessments)!
