### ISSUE TITLE
Missing Alignment to CEDS: Calendar Event Date (001275)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#175]
CEDS element 001275 (Calendar Event Date) as referenced by domain entity K12 -> Calendar -> Event in the OESE ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Remap /CalendarDate/@Date to 001275 (Calendar Event Date) not 000243 (School Year).

**Comment by ajackl** [comment]
Object Referenced in Ticket: http://specification.sifassociation.org/Implementation/NA/4.3/StudentInformationSystemsWorkingGroup.html#obj:CalendarDate

**Comment by ajackl** [comment]
NATB Approved

**Comment by 4pins** [comment]
Added to mapping (Session)!

Is "Session" the right place?

**Comment by 4pins** [comment]
Move to Attendance in mapping!

**Comment by 4pins** [comment]
Moved with note to see equivalents in StudentAttendanceSummary.

I believe this to be done!
