### ISSUE TITLE
Missing Alignment to CEDS: Charter School Contract Id Number (001651)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#176]
CEDS element 001651 (Charter School Contract Id Number) as referenced by domain entity K12 -> K12 School -> Directory in the Charter School ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Should really live here:   /SchoolInfo/SchoolCharter

**Comment by ajackl** [comment]
Object (in this case a type) Reference din the Ticket: http://specification.sifassociation.org/Implementation/NA/4.3/CommonTypes.html#SchoolCharterType

**Comment by ajackl** [comment]
NATB Approved.

**Comment by 4pins** [comment]
Added to mapping (Directory)!

**Comment by 4pins** [comment]
Normative changes were indeed made in NADM 4.3.  Closing ticket!
