### ISSUE TITLE
Missing Alignment to CEDS: Race (001943)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#177]
CEDS element 001943 (Race) as referenced by domain entity K12 -> K12Student -> Demographic in the many of the ETL Checklists (e.g. Assessment, Base IDEA, Child Count, Discipline,  etc)  is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Alignment should be: /StudentPersonals​/StudentPersonal​/Demographics​/RaceList​/Race​/Code

**Comment by 4pins** [comment]
Added to mapping (Demographic)!
