### ISSUE TITLE
Missing Alignment to CEDS: EDFacts Academic or Career and Technical Outcome Type (001978)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#178]
CEDS element 001978 (EDFacts Academic or Career and Technical Outcome Type) as referenced by domain entity K12 -> K12 Student -> Neglected or Delinquent in the Neglected or Delinquent ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Ask the NATB to consider how this fits into the StudentCareerTechnical object.

**Comment by ajackl** [comment]
Object referenced in the Ticket: http://specification.sifassociation.org/Implementation/NA/4.3/SpecialProgramsWorkingGroup.html#obj:StudentCareerTechnical

**Comment by ajackl** [comment]
NATB recommends adding a Neglected or Delinquent Type to the  StudentCareerTechnical object

**Comment by 4pins** [comment]
Added NeglectedOrDelinquentProgramType from CEDS, please double check that this is what the NATB wanted.

https://ceds.ed.gov/element/000194

**Comment by 4pins** [comment]
Added to mapping (Career and Tech Ed)!

**Comment by 4pins** [comment]
Normative changes were indeed made in NADM 4.3.  Closing ticket!
