### ISSUE TITLE
Missing Alignment to CEDS: EDFacts Academic or Career and Technical Outcome Exit Type (001979)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#179]
CEDS element 001979 (EDFacts Academic or Career and Technical Outcome Type) as referenced by domain entity K12 -> K12 Student -> Neglected or Delinquent in the Neglected or Delinquent ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment]
Ask the NATB to consider how this fits into the StudentCareerTechnical object.

**Comment by 4pins** [comment]
Note:  The "90 days after" requirement makes it clear to me that the StudentCareerTechnical object is the best place to consider adding this to our model!

**Comment by ajackl** [comment]
Object referenced  in Ticket Here: 
http://specification.sifassociation.org/Implementation/NA/4.3/SpecialProgramsWorkingGroup.html#obj:StudentCareerTechnical

**Comment by ajackl** [comment]
Initial Comment references incorrect issue.   The actual issue is adding Outcome and Outcome Exit type (as defined in CEDS#001979) to the Technical and Career Object.

**Comment by ajackl** [comment]
NATB Approves (vetted with North Carolina member)

**Comment by 4pins** [comment]
Added to mapping (Career and Tech Ed)!

**Comment by 4pins** [comment]
Normative changes were indeed made in NADM 4.3.  Closing ticket!
