### ISSUE TITLE
GPB: ScorePointsFloat and ScoreEmptyReason

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#180]
GradingAssignmentScore Object
•New conditional elements ScorePointsFloat and ScoreEmptyReason
•Conditionally required that one or more of ScorePoints, ScorePercent, ScoreLetter, ScorePointsFloat or ScoreEmptyReason be present. 
•ScoreEmptyReason: Allowed values are Excused, Unexcused, Late, and any value from CEDS Element 000934 (Learner Action Type).

**Comment by ajackl** [comment]
Link to GradeAssignmentScore Object: http://specification.sifassociation.org/Implementation/NA/4.3/GradeBookWorkingGroup.html#obj:GradingAssignmentScore

**Comment by tqwhite** [comment]
NATB Meeting 7/21/22 reviewed and approve.

**Comment by 4pins** [comment]
Normative changes were indeed made in NADM 4.3. Guidance document in first draft. Closing ticket!
