### ISSUE TITLE
CEDS / Unity Alignment Minutia

### ISSUE THREAD

**Issue by rpp9999** [Access4LearningNA/specgen_input_na#28]
StateProvinceId in StaffPersonal
CEDS URL is https://ceds.ed.gov/element/000364
This CEDS element is Classroom Identifier

**Comment by rpp9999** [comment]
While this appears to be a mis-alignment, my assessment ignores the greater picture.  StateProvinceId is used across several objects, and this may be a clear example of an identified problem, and a standard way of dealing with this situation should be devised and documented.

**Comment by 4pins** [comment]
Roger is this a State Request?

**Comment by rpp9999** [comment]
This should be ignored.

**Comment by rpp9999** [comment]
Closing this entry
