### ISSUE TITLE
Region Indicator

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#30]
NC is asking for support for a state defined region withing the state.  We have these in WA and they usually comprise multiple counties.  NC says that have numbers 1-8 while WA uses larger numbers such as 189.  I believe the reason WA states are all over the place is they are issued an LEA number, the same as a school district.

**Comment by rpp9999** [comment]
Does this refer to a state-defined geographical region, or does this refer to a regional education agency system?
The state of Iowa has various state-defined regions for various reasons, programs, and structures, and the geographical divisions differ across those uses.
The state of Iowa also has a regional education agency network, with regional agencies providing support to the districts within their region.

**Comment by 4pins** [comment]
I didn't realize there may be multiple of these.  I don't know!

**Comment by rpp9999** [comment]
Sorry.  I guess we should start with the use case and work from there - maybe they just need an identifier field that points to a state-specific code set.

**Comment by 4pins** [comment]
North Carolina needs to track region membership and through my conversations with the them and the CEDS team, we have identified there are often multiple kinds of regions to track.

See: CEDStandards/CEDS-Elements#21

**Comment by 4pins** [comment]
LEAInfo
  RegionList
    Region
    - Indicator
    - Type

189 Service/Support Regions (AEAs, ESDs, RDCs)
4 Regional Accountability Coordinator (RACs)
2 State Board Representation
1 English Language Learners Accountability

Because jargon varies state by state, the Type needs to be left free field.

**Comment by 4pins** [comment]
eScholar: RegionOrganizationCode

**Comment by 4pins** [comment]
Here is what I have added to LEAInfo:
![Screen Shot 2021-05-21 at 10 48 41 AM](https://user-images.githubusercontent.com/10967355/119178951-332ad980-ba23-11eb-8203-12229ca45b3e.png)
![Screen Shot 2021-05-21 at 10 49 38 AM](https://user-images.githubusercontent.com/10967355/119178966-3625ca00-ba23-11eb-901d-e04c9969960c.png)

**Comment by rpp9999** [comment]
This implementation looks good to me.
Link to 4.3 -- http://specification.sifassociation.org/Implementation/NA/4.3/StudentInformationSystemsWorkingGroup.html#obj:LEAInfo

**Comment by 4pins** [comment]
Confirmed in release.

Closing.
