### ISSUE TITLE
School Designation Type

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#31]
NC's List (add a field to SchoolInfo?)
C = Charter
F = Federal
L = Labortory
P = Public
O = Other
R = Regional School

**Comment by 4pins** [comment]
See:  https://github.com/CEDStandards/CEDS-Elements/issues/22

**Comment by rpp9999** [comment]
This could be useful, would want to compare/contrast this with SchoolInfo elements SchoolType and SchoolFocusList, I assume a school could have multiple designations

**Comment by 4pins** [comment]
Potential new name: Educational Agency Type

**Comment by 4pins** [comment]
Apply to School & LEA.

**Comment by 4pins** [comment]
LEAInfo already has EducationAgencyType while SchoolInfo does not.  Is that what we want?  Do we want a suplimental list?

**Comment by 4pins** [comment]
SchoolInfo & LEAInfo
SchoolDesignationList
- Code
- @Codeset

**Comment by 4pins** [comment]
Create the types but haven't added them to the objects (or tested them) yet.

**Comment by 4pins** [comment]
Does this match expectations?

![Screen Shot 2021-07-16 at 2 00 01 PM](https://user-images.githubusercontent.com/10967355/126008013-8f0cf9ff-00df-49ea-8703-a702164a71bb.png)

**Comment by 4pins** [comment]
Waiting for CEDS before doing any further realignment.
At this point DO NOT CLOSE!

**Comment by 4pins** [comment]
Is this related to:  https://github.com/CEDStandards/CEDS-Elements/issues/112

**Comment by 4pins** [comment]
CEDS 10 came out today, they have not yet completed there related work.  So we would like the NATB to consider inclusion as is in support of North Carolina's needs.

**Comment by 4pins** [comment]
Pay attention to:  https://github.com/Access4LearningNA/specgen_input_na/issues/176
Also see:  /SchoolInfo/SchoolCharter

**Comment by 4pins** [comment]
Duplicate removed!

**Comment by rpp9999** [comment]
This implementation looks good to me.

Link to 4.3 LEAInfo -- http://specification.sifassociation.org/Implementation/NA/4.3/StudentInformationSystemsWorkingGroup.html#obj:LEAInfo
Link to 4.3 SchoolInfo -- http://specification.sifassociation.org/Implementation/NA/4.3/StudentInformationSystemsWorkingGroup.html#obj:SchoolInfo

**Comment by 4pins** [comment]
Confirmed in release.

Closing.
