### ISSUE TITLE
HR Benefit Eligibility

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#39]
Also from NC, the other side of hours adding up to to an FTE is a way to check that the employee can get their benefits when they qualify.  The suggestion is to add a BenefitEligibility indicator to EmployeePersonal.

**Comment by 4pins** [comment]
CEDS:  https://github.com/CEDStandards/CEDS-Elements/issues/74

**Comment by 4pins** [comment]
Also check on...
CEDS:  https://github.com/CEDStandards/CEDS-Elements/issues/73

**Comment by 4pins** [comment]
Don't worry about the CEDS elements they still want a BenefitEligibility indicator on EmployeePersonal.

**Comment by 4pins** [comment]
First try!
<img width="296" alt="Screen Shot 2021-08-30 at 11 55 40 AM" src="https://user-images.githubusercontent.com/10967355/131390331-62785e25-e9be-4a5d-a99c-05d4ab391434.png">
Note:  Yes/No/Unknown

**Comment by 4pins** [comment]
Since we cannot depend on this being calculated by the component objects (different rules based on the position, negotiated in contract, etc.) this needs to be a settable data field at this level in the hierarchy.

**Comment by 4pins** [comment]
Dig into CEDS 9 changes a little deeper and bring back to the NATB.

**Comment by 4pins** [comment]
NATB approved!

**Comment by ajackl** [comment]
Object referenced in this Ticket: http://specification.sifassociation.org/Implementation/NA/4.3/HumanResourcesFinancialsWorkingGroup.html#obj:EmployeePersonal

**Comment by ajackl** [comment]
The NATB Approves this AND  we do not want this included in Staff Personal since  StaffPersonal has a reference to EmployeePersonal so that is handled.

**Comment by 4pins** [comment]
Confirmed included in release.

Closing.
