### ISSUE TITLE
HR Retired Indicator

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#41]
Request by NC, however I have experienced this in WA, sometimes an employee is also permitted to be retired (sometimes not).  This has various impacts, the most common being a retirement check and pay check and this needs to be closely watched by the state.  The suggestion is to add a Retired indicator to the EmployeePersonal, so that systems can do what policy dictates in these situations.

**Comment by 4pins** [comment]
See:  https://github.com/CEDStandards/CEDS-Elements/issues/178

**Comment by 4pins** [comment]
Field name:  ReemployedRetiree

**Comment by 4pins** [comment]
On hold while we look at Open HR.

**Comment by ajackl** [comment]
Object Referenced in this  Ticket:  http://specification.sifassociation.org/Implementation/NA/4.3/HumanResourcesFinancialsWorkingGroup.html#obj:EmployeePersonal

**Comment by ajackl** [comment]
NATB Approves (no StaffPersonal changes- handled by reference)

**Comment by 4pins** [comment]
Confirmed present in release.

Closing.
