### ISSUE TITLE
RaceDeclined

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#59]
NC: Want to know when the race was determined by a staff member because the student/parent declined to indicate their race.

**Comment by 4pins** [comment]
CEDS:  https://github.com/CEDStandards/CEDS-Elements/issues/64

**Comment by 4pins** [comment]
The plan:  Stick it right under HispanicLatino/@CodeSet as NC proposed.
Federal Race and Ethnicity Declined
As always run by technical board.

**Comment by ajackl** [comment]
Object (in this case a Type) referenced in the Ticket: http://specification.sifassociation.org/Implementation/NA/4.3/CommonTypes.html#DemographicsType

**Comment by 4pins** [comment]
Confirmed included in NADM 4.3.

Closing.
